--------------------------------------------------------
--  文件已创建 - 星期四-三月-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPINFO
--------------------------------------------------------

  CREATE TABLE "SCOTT"."EMPINFO" 
   (	"FEMPNO" VARCHAR2(10 BYTE), 
	"FEMPNAME" VARCHAR2(20 BYTE), 
	"FAGE" NUMBER(2,0), 
	"FSALARY" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.EMPINFO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C0011143
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011143" ON "SCOTT"."EMPINFO" ("FEMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPINFO
--------------------------------------------------------

  ALTER TABLE "SCOTT"."EMPINFO" MODIFY ("FEMPNO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EMPINFO" MODIFY ("FEMPNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EMPINFO" MODIFY ("FAGE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EMPINFO" MODIFY ("FSALARY" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."EMPINFO" ADD PRIMARY KEY ("FEMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
